language: cpp
dist: xenial
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- curl -T helloworld-0.0."$TRAVIS_BUILD_NUMBER"-Linux.deb -usergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/hello-world/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
-deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0."$TRAVIS_BUILD_NUMBER"-Linux.deb -usergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/hello-world/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
